version: "3.9"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build: ./app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "main.py"]
