version: "3.9"
services:
  app:
    build: ./app
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["python", "main.py"]
