
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  ocsvm_anomaly_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app/main.py

volumes:
  mongo_data:
